name: track_that_money
description: "An Expense Tracking App to Know Why You're Broke."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  uuid: ^4.0.0
  flutter:
    sdk: flutter
  go_router: ^17.0.1
  shared_preferences: ^2.3.2
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^4.0.0
  # Networking
  http: ^1.2.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.25.15
  build_runner: ^2.4.12
  riverpod_generator: ^4.0.0+1

flutter:
  uses-material-design: true
  assets:
    - lib/data/resources_library.json
